### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [liyafe1997/FuckDevicePolicy#1]
Can you please point out what license your code is put under? Favorably it's a F/LOSS license :wink: Without license it's rather a "you might look at the code but not use it". So it would be great if a license states further permissions.

Same for your other projects. I see some use GPL-3.0, which is very fine. Does that apply here, too, and you just forgot to include it?

Thanks in advance!

**Comment by liyafe1997** [comment]
Thanks for pointing out. Now I added GPL3 as license😉

**Comment by IzzySoft** [comment]
Wonderful, thanks! That now allows me to take your module into my repository, which only allows for FOSS. With the next sync around 7 pm UTC, you will [find it here](https://apt.izzysoft.de/fdroid/index/apk/com.strawing.fuckdevicepolicy) (with the official Xposed repo down I thought it's a good idea to pick up at least the FOSS modules to be available to all Xposed variants. Of course I cannot tell if they'd work with all of them :wink:). Quick preview:

![image](https://user-images.githubusercontent.com/6781438/217012337-7e72e63a-cd36-4460-9df9-39ed1ae67e41.png)

If you had a dedicated icon for your app, that would be shown in the upper left corner, were the first paragraph looks like having some "funny formatting". Just let me know then and I'll integrate it. Of course you then also could replace the "default Andy bot" in your `ic_launcher.webp` files of the `res` tree :wink:

PS: I gladly provide you the metadata set up here using [Fastlane structures](https://gitlab.com/-/snippets/1895688) per PR if you want them in your repo, so you can adjust them to your needs. My updater (running once a day) would then fetch that along with each new release you make.
